# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bd:
    image: db
    hostname: 'db'
    build:
      context: ./Db/
      dockerfile: Dockerfile
    ports:
      - 3306:3306